apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::538492273234:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::538492273234:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1GETYMFD6X0UX
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-17T19:35:19Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1615"
  uid: 649ce86e-3862-4401-bf40-ac6ae9e7db1f
