apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::538492273234:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::538492273234:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1LYKTT21VG0QU
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-18T08:18:32Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1684"
  uid: a9f04944-22ca-406b-90a1-22ed49097f42
